theme = "kanagawa-noitalic"

[editor]
default-yank-register = "+"
line-number = "relative"
mouse = true
bufferline = "multiple"
cursorline = true
color-modes = true
completion-timeout = 5
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control", "file-name", "file-modification-indicator", "read-only-indicator"]
right = ["file-type", "spacer", "separator", "spacer", "file-encoding", "file-line-ending", "spacer", "separator", "spacer", "position", "position-percentage"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

